### PR TITLE
Correct var name for creating user accounts from orders.

### LINKED ISSUE #1: Undefined variable $create_users causing no users to be created
There's a bug in here where the query string passed is `create_users`, and we assign that like this:
`$create   = isset( $_GET['create_users'] ) ? absint( $_GET['create_users'] ) : 0;`

However in the loop, it's looking for `$create_users`
`if ( $create_users ){`

### PR DESCRIPTION
**Pull request by pderksen**
Fixes #1

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@chriscct7 Could you please merge and get this pushed up to WordPress.org?

**Comment by chriscct7** [comment]
For some reason was never notified about this.

**Comment by chriscct7** [comment]
I'm going to rewrite this and thoroughly test it before updating it on .org since right now it's not actively listed in the repository (except direct) because it hasn't been updated in a while. Will try to set some time for it over the next few weeks, though tbh, this is something we should really consider building into EDD core as a tool

**Comment by pippinsplugins** [comment]
:+1:

**Comment by chriscct7** [comment]
Note we're going to private the download on EDD's site and set it to published once its update goes out

**Pull request merged**
